# Default values for inlets_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: inlets/inlets
  tag: 2.7.0
  pullPolicy: Always

useSecurityContext: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  host: chart-example.local
  tls: false

inlets_use_token: true
inlets_token: "changeme"

resources:
  limits:
    cpu: 25m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
